name: medicare-aca-compliance
region: nyc
services:
  - name: web
    environment_slug: node-js
    github:
      repo: bbarnes4318/compliance
      branch: main
      deploy_on_push: true
    build_command: npm ci --production=false && npm run build
    run_command: npm start
    http_port: 3000
    instance_count: 2
    instance_size_slug: professional-xs
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: ENCRYPTION_KEY
        scope: RUN_TIME
        type: SECRET
    alerts:
      - rule: DEPLOYMENT_FAILED
      - rule: DOMAIN_FAILED
      - rule: CPU_UTILIZATION
        value: 85
        window: 5m
      - rule: MEM_UTILIZATION
        value: 85
        window: 5m

databases:
  - name: compliance-db
    engine: PG
    version: "15"
    size: db-s-1vcpu-2gb
    num_nodes: 1
    production: true
  - name: compliance-cache
    engine: REDIS
    version: "7"
    size: db-s-1vcpu-1gb
    num_nodes: 1

jobs:
  - name: daily-screening
    kind: PRE_DEPLOY
    github:
      repo: bbarnes4318/compliance
      branch: main
    run_command: npm run screening:daily
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
  
  - name: monthly-audit
    kind: POST_DEPLOY
    github:
      repo: bbarnes4318/compliance
      branch: main
    run_command: npm run audit:monthly
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET